### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by crzidea** [rnicrosoft/windows#3]
What is going on here? I found this repo was created two years ago. But there is only the README.md here. What's the purpose of this repo?

**Comment by cpixelcube** [comment]
The creator of this repo is "r nicrosoft", not "microsoft" chances are it was going to be used to fool people into thinking Windows is open-source.

**Comment by crzidea** [comment]
I think I was fooled for a very long time.

**Comment by icecoobe** [comment]
lol,  me 2

**Comment by Articuno1234** [comment]
really? i noticed strait away XD
